# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1017, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblGraphic = QtWidgets.QLabel(self.centralwidget)
        self.lblGraphic.setMinimumSize(QtCore.QSize(300, 300))
        self.lblGraphic.setFrameShape(QtWidgets.QFrame.Box)
        self.lblGraphic.setText("")
        self.lblGraphic.setPixmap(QtGui.QPixmap("../../example.png"))
        self.lblGraphic.setObjectName("lblGraphic")
        self.verticalLayout_6.addWidget(self.lblGraphic)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblVerPos = QtWidgets.QLabel(self.groupBox_5)
        self.lblVerPos.setObjectName("lblVerPos")
        self.verticalLayout_5.addWidget(self.lblVerPos)
        self.lblHorPos = QtWidgets.QLabel(self.groupBox_5)
        self.lblHorPos.setObjectName("lblHorPos")
        self.verticalLayout_5.addWidget(self.lblHorPos)
        self.lblV = QtWidgets.QLabel(self.groupBox_5)
        self.lblV.setObjectName("lblV")
        self.verticalLayout_5.addWidget(self.lblV)
        self.lblCur = QtWidgets.QLabel(self.groupBox_5)
        self.lblCur.setObjectName("lblCur")
        self.verticalLayout_5.addWidget(self.lblCur)
        self.line_4 = QtWidgets.QFrame(self.groupBox_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.lblPollRate = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.lblPollRate.setFont(font)
        self.lblPollRate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPollRate.setObjectName("lblPollRate")
        self.verticalLayout_5.addWidget(self.lblPollRate)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lblVerPos_2 = QtWidgets.QLabel(self.groupBox_3)
        self.lblVerPos_2.setObjectName("lblVerPos_2")
        self.verticalLayout_12.addWidget(self.lblVerPos_2)
        self.line_7 = QtWidgets.QFrame(self.groupBox_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_12.addWidget(self.line_7)
        self.label_57 = QtWidgets.QLabel(self.groupBox_3)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_12.addWidget(self.label_57)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_13.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_13.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_13.addWidget(self.radioButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_12.addWidget(self.label_42)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_14.addWidget(self.lineEdit)
        self.label_56 = QtWidgets.QLabel(self.groupBox_3)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_14.addWidget(self.label_56)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.gridLayout_6.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lblVerPos_5 = QtWidgets.QLabel(self.groupBox_8)
        self.lblVerPos_5.setObjectName("lblVerPos_5")
        self.gridLayout_13.addWidget(self.lblVerPos_5, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_13.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.lblVerPos_7 = QtWidgets.QLabel(self.groupBox_8)
        self.lblVerPos_7.setObjectName("lblVerPos_7")
        self.gridLayout_13.addWidget(self.lblVerPos_7, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_8, 3, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_39 = QtWidgets.QLabel(self.groupBox_11)
        self.label_39.setObjectName("label_39")
        self.gridLayout_9.addWidget(self.label_39, 0, 0, 1, 1)
        self.txtIP = QtWidgets.QLineEdit(self.groupBox_11)
        self.txtIP.setInputMask("")
        self.txtIP.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIP.setObjectName("txtIP")
        self.gridLayout_9.addWidget(self.txtIP, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_11)
        self.label_40.setObjectName("label_40")
        self.gridLayout_9.addWidget(self.label_40, 1, 0, 1, 1)
        self.txtPort = QtWidgets.QLineEdit(self.groupBox_11)
        self.txtPort.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPort.setObjectName("txtPort")
        self.gridLayout_9.addWidget(self.txtPort, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.btnConnect = QtWidgets.QPushButton(self.groupBox_11)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_11.addWidget(self.btnConnect)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.lblServerMsg = QtWidgets.QLabel(self.groupBox_11)
        self.lblServerMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblServerMsg.setObjectName("lblServerMsg")
        self.verticalLayout_11.addWidget(self.lblServerMsg)
        self.horizontalLayout_12.addLayout(self.verticalLayout_11)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.gridLayout_6.addWidget(self.groupBox_11, 0, 0, 1, 2)
        self.line_6 = QtWidgets.QFrame(self.tab_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_6.addWidget(self.line_6, 1, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lblVerPos_3 = QtWidgets.QLabel(self.groupBox_4)
        self.lblVerPos_3.setObjectName("lblVerPos_3")
        self.gridLayout_11.addWidget(self.lblVerPos_3, 0, 0, 1, 1)
        self.btnVStepTest = QtWidgets.QPushButton(self.groupBox_4)
        self.btnVStepTest.setObjectName("btnVStepTest")
        self.gridLayout_11.addWidget(self.btnVStepTest, 1, 0, 1, 1)
        self.lblVerPos_6 = QtWidgets.QLabel(self.groupBox_4)
        self.lblVerPos_6.setObjectName("lblVerPos_6")
        self.gridLayout_11.addWidget(self.lblVerPos_6, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lblVerPos_4 = QtWidgets.QLabel(self.groupBox_10)
        self.lblVerPos_4.setObjectName("lblVerPos_4")
        self.gridLayout_12.addWidget(self.lblVerPos_4, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_12.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.lblVerPos_8 = QtWidgets.QLabel(self.groupBox_10)
        self.lblVerPos_8.setObjectName("lblVerPos_8")
        self.gridLayout_12.addWidget(self.lblVerPos_8, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_10, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbVMove = QtWidgets.QRadioButton(self.groupBox)
        self.rbVMove.setChecked(True)
        self.rbVMove.setObjectName("rbVMove")
        self.horizontalLayout.addWidget(self.rbVMove)
        self.rbHMove = QtWidgets.QRadioButton(self.groupBox)
        self.rbHMove.setObjectName("rbHMove")
        self.horizontalLayout.addWidget(self.rbHMove)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 0, 1, 1)
        self.txtMoveV = QtWidgets.QLineEdit(self.groupBox)
        self.txtMoveV.setText("")
        self.txtMoveV.setMaxLength(20)
        self.txtMoveV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMoveV.setObjectName("txtMoveV")
        self.gridLayout_2.addWidget(self.txtMoveV, 1, 1, 1, 1)
        self.txtMovePos = QtWidgets.QLineEdit(self.groupBox)
        self.txtMovePos.setText("")
        self.txtMovePos.setMaxLength(20)
        self.txtMovePos.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMovePos.setObjectName("txtMovePos")
        self.gridLayout_2.addWidget(self.txtMovePos, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.btnCalibMoveSet = QtWidgets.QPushButton(self.groupBox)
        self.btnCalibMoveSet.setObjectName("btnCalibMoveSet")
        self.horizontalLayout_4.addWidget(self.btnCalibMoveSet)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setItalic(True)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_3.addWidget(self.label_41)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.btnRetract = QtWidgets.QPushButton(self.groupBox)
        self.btnRetract.setObjectName("btnRetract")
        self.horizontalLayout_7.addWidget(self.btnRetract)
        self.btnExtend = QtWidgets.QPushButton(self.groupBox)
        self.btnExtend.setObjectName("btnExtend")
        self.horizontalLayout_7.addWidget(self.btnExtend)
        self.btnStop = QtWidgets.QPushButton(self.groupBox)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_7.addWidget(self.btnStop)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_55 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setItalic(True)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_9.addWidget(self.label_55)
        self.gbVCalib = QtWidgets.QGroupBox(self.groupBox_7)
        self.gbVCalib.setObjectName("gbVCalib")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gbVCalib)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_44 = QtWidgets.QLabel(self.gbVCalib)
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 0, 0, 1, 1)
        self.btnVExtend = QtWidgets.QPushButton(self.gbVCalib)
        self.btnVExtend.setEnabled(True)
        self.btnVExtend.setObjectName("btnVExtend")
        self.gridLayout_7.addWidget(self.btnVExtend, 0, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gbVCalib)
        self.label_47.setObjectName("label_47")
        self.gridLayout_7.addWidget(self.label_47, 0, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gbVCalib)
        self.label_48.setObjectName("label_48")
        self.gridLayout_7.addWidget(self.label_48, 1, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gbVCalib)
        self.label_45.setObjectName("label_45")
        self.gridLayout_7.addWidget(self.label_45, 1, 0, 1, 1)
        self.btnVParked = QtWidgets.QPushButton(self.gbVCalib)
        self.btnVParked.setEnabled(True)
        self.btnVParked.setObjectName("btnVParked")
        self.gridLayout_7.addWidget(self.btnVParked, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.gbVCalib)
        self.gbHCalib = QtWidgets.QGroupBox(self.groupBox_7)
        self.gbHCalib.setEnabled(False)
        self.gbHCalib.setObjectName("gbHCalib")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gbHCalib)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_51 = QtWidgets.QLabel(self.gbHCalib)
        self.label_51.setObjectName("label_51")
        self.gridLayout_8.addWidget(self.label_51, 0, 0, 1, 1)
        self.btnHExtend = QtWidgets.QPushButton(self.gbHCalib)
        self.btnHExtend.setEnabled(False)
        self.btnHExtend.setObjectName("btnHExtend")
        self.gridLayout_8.addWidget(self.btnHExtend, 0, 1, 1, 1)
        self.btnHParked = QtWidgets.QPushButton(self.gbHCalib)
        self.btnHParked.setEnabled(False)
        self.btnHParked.setObjectName("btnHParked")
        self.gridLayout_8.addWidget(self.btnHParked, 1, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gbHCalib)
        self.label_53.setObjectName("label_53")
        self.gridLayout_8.addWidget(self.label_53, 1, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gbHCalib)
        self.label_54.setObjectName("label_54")
        self.gridLayout_8.addWidget(self.label_54, 1, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gbHCalib)
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 0, 2, 1, 1)
        self.verticalLayout_9.addWidget(self.gbHCalib)
        self.line_8 = QtWidgets.QFrame(self.groupBox_7)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_9.addWidget(self.line_8)
        self.gbHCalib_2 = QtWidgets.QGroupBox(self.groupBox_7)
        self.gbHCalib_2.setEnabled(True)
        self.gbHCalib_2.setObjectName("gbHCalib_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gbHCalib_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_58 = QtWidgets.QLabel(self.gbHCalib_2)
        self.label_58.setObjectName("label_58")
        self.gridLayout_10.addWidget(self.label_58, 0, 0, 1, 1)
        self.btnHExtend_2 = QtWidgets.QPushButton(self.gbHCalib_2)
        self.btnHExtend_2.setEnabled(True)
        self.btnHExtend_2.setObjectName("btnHExtend_2")
        self.gridLayout_10.addWidget(self.btnHExtend_2, 1, 1, 1, 1)
        self.btnHCenter_2 = QtWidgets.QPushButton(self.gbHCalib_2)
        self.btnHCenter_2.setObjectName("btnHCenter_2")
        self.gridLayout_10.addWidget(self.btnHCenter_2, 0, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.gbHCalib_2)
        self.label_60.setObjectName("label_60")
        self.gridLayout_10.addWidget(self.label_60, 1, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.gbHCalib_2)
        self.horizontalLayout_10.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.btnChooseFile = QtWidgets.QPushButton(self.groupBox_6)
        self.btnChooseFile.setObjectName("btnChooseFile")
        self.horizontalLayout_6.addWidget(self.btnChooseFile)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rbVScan = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbVScan.setChecked(True)
        self.rbVScan.setObjectName("rbVScan")
        self.horizontalLayout_8.addWidget(self.rbVScan)
        self.rbHScan = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbHScan.setObjectName("rbHScan")
        self.horizontalLayout_8.addWidget(self.rbHScan)
        self.rbBothScan = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbBothScan.setObjectName("rbBothScan")
        self.horizontalLayout_8.addWidget(self.rbBothScan)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gbVScan = QtWidgets.QGroupBox(self.groupBox_2)
        self.gbVScan.setObjectName("gbVScan")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbVScan)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.gbVScan)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtVMinPos = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVMinPos.setObjectName("txtVMinPos")
        self.gridLayout_3.addWidget(self.txtVMinPos, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbVScan)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtVMaxPos = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVMaxPos.setObjectName("txtVMaxPos")
        self.gridLayout_3.addWidget(self.txtVMaxPos, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gbVScan)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gbVScan)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtVStepPos = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVStepPos.setObjectName("txtVStepPos")
        self.gridLayout_3.addWidget(self.txtVStepPos, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gbVScan)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gbVScan)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gbVScan)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line = QtWidgets.QFrame(self.gbVScan)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.gbVScan)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gbVScan)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gbVScan)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.txtVMaxV = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVMaxV.setObjectName("txtVMaxV")
        self.gridLayout.addWidget(self.txtVMaxV, 1, 1, 1, 1)
        self.txtVStepV = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVStepV.setObjectName("txtVStepV")
        self.gridLayout.addWidget(self.txtVStepV, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gbVScan)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.txtVMinV = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVMinV.setObjectName("txtVMinV")
        self.gridLayout.addWidget(self.txtVMinV, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gbVScan)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gbVScan)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 1, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gbVScan)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.gbVScan)
        self.gbHScan = QtWidgets.QGroupBox(self.groupBox_2)
        self.gbHScan.setEnabled(False)
        self.gbHScan.setObjectName("gbHScan")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbHScan)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.gbHScan)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txtHMinPos = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHMinPos.setObjectName("txtHMinPos")
        self.gridLayout_4.addWidget(self.txtHMinPos, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gbHScan)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gbHScan)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.txtHMaxPos = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHMaxPos.setObjectName("txtHMaxPos")
        self.gridLayout_4.addWidget(self.txtHMaxPos, 1, 1, 1, 1)
        self.txtHStepPos = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHStepPos.setObjectName("txtHStepPos")
        self.gridLayout_4.addWidget(self.txtHStepPos, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gbHScan)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gbHScan)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gbHScan)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gbHScan)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.line_2 = QtWidgets.QFrame(self.gbHScan)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_14 = QtWidgets.QLabel(self.gbHScan)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txtHMaxV = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHMaxV.setObjectName("txtHMaxV")
        self.gridLayout_5.addWidget(self.txtHMaxV, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gbHScan)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.txtHMinV = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHMinV.setObjectName("txtHMinV")
        self.gridLayout_5.addWidget(self.txtHMinV, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gbHScan)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gbHScan)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 2, 0, 1, 1)
        self.txtHStepV = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHStepV.setObjectName("txtHStepV")
        self.gridLayout_5.addWidget(self.txtHStepV, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gbHScan)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 0, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gbHScan)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 1, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gbHScan)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout_2.addWidget(self.gbHScan)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.btnStartStopScan = QtWidgets.QPushButton(self.groupBox_2)
        self.btnStartStopScan.setObjectName("btnStartStopScan")
        self.horizontalLayout_3.addWidget(self.btnStartStopScan)
        self.btnContinueScan = QtWidgets.QPushButton(self.groupBox_2)
        self.btnContinueScan.setObjectName("btnContinueScan")
        self.horizontalLayout_3.addWidget(self.btnContinueScan)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lblScanStatus = QtWidgets.QLabel(self.groupBox_9)
        self.lblScanStatus.setMinimumSize(QtCore.QSize(300, 300))
        self.lblScanStatus.setFrameShape(QtWidgets.QFrame.Box)
        self.lblScanStatus.setText("")
        self.lblScanStatus.setObjectName("lblScanStatus")
        self.verticalLayout_10.addWidget(self.lblScanStatus)
        self.label_21 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_10.addWidget(self.label_21)
        self.label_23 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_10.addWidget(self.label_23)
        self.label_38 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_10.addWidget(self.label_38)
        self.label_22 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_10.addWidget(self.label_22)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem15)
        self.horizontalLayout_9.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1017, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad_Calibration = QtWidgets.QAction(MainWindow)
        self.actionLoad_Calibration.setObjectName("actionLoad_Calibration")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menuFile.addAction(self.actionLoad_Calibration)
        self.menuFile.addAction(self.action_Exit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Current Values"))
        self.lblVerPos.setText(_translate("MainWindow", "Vertical: -- (Not calibrated)"))
        self.lblHorPos.setText(_translate("MainWindow", "Horizontal: -- (Not calibrated)"))
        self.lblV.setText(_translate("MainWindow", "Voltage: --"))
        self.lblCur.setText(_translate("MainWindow", "Current: --"))
        self.lblPollRate.setText(_translate("MainWindow", "Polling rate: --"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Picoammeter"))
        self.lblVerPos_2.setText(_translate("MainWindow", "Device Found"))
        self.label_57.setText(_translate("MainWindow", "Sample rate"))
        self.radioButton_3.setText(_translate("MainWindow", "Fast"))
        self.radioButton_2.setText(_translate("MainWindow", "Medium"))
        self.radioButton.setText(_translate("MainWindow", "Slow"))
        self.label_42.setText(_translate("MainWindow", "Averaging"))
        self.lineEdit.setText(_translate("MainWindow", "1"))
        self.label_56.setText(_translate("MainWindow", "Samples"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Horizontal Stepper"))
        self.lblVerPos_5.setText(_translate("MainWindow", "Device Found"))
        self.pushButton_5.setText(_translate("MainWindow", "Send test signal"))
        self.lblVerPos_7.setText(_translate("MainWindow", "Response: Ok!"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Server"))
        self.label_39.setText(_translate("MainWindow", "IP"))
        self.txtIP.setText(_translate("MainWindow", "10.77.0.4"))
        self.label_40.setText(_translate("MainWindow", "Port"))
        self.txtPort.setText(_translate("MainWindow", "5000"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.lblServerMsg.setText(_translate("MainWindow", "Unable to connect"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Vertical Stepper"))
        self.lblVerPos_3.setText(_translate("MainWindow", "Device Found"))
        self.btnVStepTest.setText(_translate("MainWindow", "Send test signal"))
        self.lblVerPos_6.setText(_translate("MainWindow", "Response: Ok!"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Voltage Regulator"))
        self.lblVerPos_4.setText(_translate("MainWindow", "Device Found"))
        self.pushButton_6.setText(_translate("MainWindow", "Send test signal"))
        self.lblVerPos_8.setText(_translate("MainWindow", "Response: Ok!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Communication"))
        self.groupBox.setTitle(_translate("MainWindow", "Move"))
        self.rbVMove.setText(_translate("MainWindow", "Vertical"))
        self.rbHMove.setText(_translate("MainWindow", "Horizontal"))
        self.label_20.setText(_translate("MainWindow", "Voltage"))
        self.label_19.setText(_translate("MainWindow", "Position"))
        self.label_24.setText(_translate("MainWindow", "Steps"))
        self.label_25.setText(_translate("MainWindow", "V (-10 to +10)"))
        self.btnCalibMoveSet.setText(_translate("MainWindow", "Go"))
        self.label_41.setText(_translate("MainWindow", "Or"))
        self.btnRetract.setText(_translate("MainWindow", "Retract"))
        self.btnExtend.setText(_translate("MainWindow", "Extend"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Calibrate"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p>Move the motor to the corresponding position</p><p>Center is considered to be the origin (0cm)</p></body></html>"))
        self.gbVCalib.setTitle(_translate("MainWindow", "Vertical (Not calibrated)"))
        self.label_44.setText(_translate("MainWindow", "Extended"))
        self.btnVExtend.setText(_translate("MainWindow", "Set"))
        self.label_47.setText(_translate("MainWindow", "--"))
        self.label_48.setText(_translate("MainWindow", "--"))
        self.label_45.setText(_translate("MainWindow", "Parked"))
        self.btnVParked.setText(_translate("MainWindow", "Set"))
        self.gbHCalib.setTitle(_translate("MainWindow", "Horizontal (Not calibrated)"))
        self.label_51.setText(_translate("MainWindow", "Extended"))
        self.btnHExtend.setText(_translate("MainWindow", "Set"))
        self.btnHParked.setText(_translate("MainWindow", "Set"))
        self.label_53.setText(_translate("MainWindow", "Parked"))
        self.label_54.setText(_translate("MainWindow", "--"))
        self.label_52.setText(_translate("MainWindow", "--"))
        self.gbHCalib_2.setTitle(_translate("MainWindow", "Voltage"))
        self.label_58.setText(_translate("MainWindow", "-10 V"))
        self.btnHExtend_2.setText(_translate("MainWindow", "Set"))
        self.btnHCenter_2.setText(_translate("MainWindow", "Set"))
        self.label_60.setText(_translate("MainWindow", "+10 V"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calibration"))
        self.groupBox_6.setTitle(_translate("MainWindow", "File Options"))
        self.btnChooseFile.setText(_translate("MainWindow", "Choose Output File"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Scan"))
        self.rbVScan.setText(_translate("MainWindow", "Vertical"))
        self.rbHScan.setText(_translate("MainWindow", "Horizontal"))
        self.rbBothScan.setText(_translate("MainWindow", "Both"))
        self.gbVScan.setTitle(_translate("MainWindow", "Vertical Scan"))
        self.label_5.setText(_translate("MainWindow", "Motor"))
        self.label_3.setText(_translate("MainWindow", "Max"))
        self.label_2.setText(_translate("MainWindow", "Min"))
        self.label_4.setText(_translate("MainWindow", "Step"))
        self.label_26.setText(_translate("MainWindow", "cm"))
        self.label_27.setText(_translate("MainWindow", "cm"))
        self.label_28.setText(_translate("MainWindow", "cm"))
        self.label_6.setText(_translate("MainWindow", "Voltage"))
        self.label_7.setText(_translate("MainWindow", "Min"))
        self.label_8.setText(_translate("MainWindow", "Max"))
        self.label_9.setText(_translate("MainWindow", "Step"))
        self.label_32.setText(_translate("MainWindow", "kV"))
        self.label_33.setText(_translate("MainWindow", "kV"))
        self.label_34.setText(_translate("MainWindow", "kV"))
        self.gbHScan.setTitle(_translate("MainWindow", "Horizontal Scan"))
        self.label_10.setText(_translate("MainWindow", "Motor"))
        self.label_11.setText(_translate("MainWindow", "Min"))
        self.label_12.setText(_translate("MainWindow", "Max"))
        self.label_13.setText(_translate("MainWindow", "Step"))
        self.label_29.setText(_translate("MainWindow", "cm"))
        self.label_30.setText(_translate("MainWindow", "cm"))
        self.label_31.setText(_translate("MainWindow", "cm"))
        self.label_14.setText(_translate("MainWindow", "Voltage"))
        self.label_16.setText(_translate("MainWindow", "Max"))
        self.label_15.setText(_translate("MainWindow", "Min"))
        self.label_17.setText(_translate("MainWindow", "Step"))
        self.label_35.setText(_translate("MainWindow", "kV"))
        self.label_36.setText(_translate("MainWindow", "kV"))
        self.label_37.setText(_translate("MainWindow", "kV"))
        self.label_18.setText(_translate("MainWindow", "Total points: 1000"))
        self.label.setText(_translate("MainWindow", "Output saved to /test/directory/file.csv"))
        self.btnStartStopScan.setText(_translate("MainWindow", "Start Scan"))
        self.btnContinueScan.setText(_translate("MainWindow", "Continue Scan"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Status"))
        self.label_21.setText(_translate("MainWindow", "Current: 500/1000 (50%)"))
        self.label_23.setText(_translate("MainWindow", "Vertical, +5cm"))
        self.label_38.setText(_translate("MainWindow", "Voltage: 2 kV"))
        self.label_22.setText(_translate("MainWindow", "Est. Time Remaining: 5 minutes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scan"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Calibration.setText(_translate("MainWindow", "Load Calibration"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))

