# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/MainWindow_v2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1154, 728)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("font-size: 9pt")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblGraphic = QtWidgets.QLabel(self.centralwidget)
        self.lblGraphic.setMinimumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblGraphic.setFont(font)
        self.lblGraphic.setFrameShape(QtWidgets.QFrame.Box)
        self.lblGraphic.setText("")
        self.lblGraphic.setPixmap(QtGui.QPixmap("../../Ion-Source-Control-System/Software/example.png"))
        self.lblGraphic.setObjectName("lblGraphic")
        self.verticalLayout_5.addWidget(self.lblGraphic)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color:#003399")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_17.addWidget(self.label_56)
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_15.setFont(font)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.horizontalLayout_17.addWidget(self.line_15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.lblVerPos = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblVerPos.setFont(font)
        self.lblVerPos.setObjectName("lblVerPos")
        self.verticalLayout_5.addWidget(self.lblVerPos)
        self.lblHorPos = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblHorPos.setFont(font)
        self.lblHorPos.setObjectName("lblHorPos")
        self.verticalLayout_5.addWidget(self.lblHorPos)
        self.lblV = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblV.setFont(font)
        self.lblV.setObjectName("lblV")
        self.verticalLayout_5.addWidget(self.lblV)
        self.lblCur = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblCur.setFont(font)
        self.lblCur.setObjectName("lblCur")
        self.verticalLayout_5.addWidget(self.lblCur)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("color:#003399")
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_18.addWidget(self.label_57)
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_17.setFont(font)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.horizontalLayout_18.addWidget(self.line_17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.lblServerStatus = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblServerStatus.setFont(font)
        self.lblServerStatus.setStyleSheet("color: red")
        self.lblServerStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblServerStatus.setObjectName("lblServerStatus")
        self.verticalLayout_5.addWidget(self.lblServerStatus)
        self.lblPollRate = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblPollRate.setFont(font)
        self.lblPollRate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPollRate.setObjectName("lblPollRate")
        self.verticalLayout_5.addWidget(self.lblPollRate)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("::enabled {\n"
"color:#003399;\n"
"font-size:12pt;\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"font-size:12pt;\n"
"}")
        self.label_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_12.addWidget(self.label_42)
        self.label_54 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_12.addWidget(self.label_54)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_12.addWidget(self.label_25)
        self.line_10 = QtWidgets.QFrame(self.tab_3)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_12.addWidget(self.line_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(11, -1, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_8.addWidget(self.label_39, 0, 0, 1, 1)
        self.txtIP = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtIP.sizePolicy().hasHeightForWidth())
        self.txtIP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtIP.setFont(font)
        self.txtIP.setInputMask("")
        self.txtIP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtIP.setObjectName("txtIP")
        self.gridLayout_8.addWidget(self.txtIP, 0, 1, 1, 1)
        self.txtPort = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPort.sizePolicy().hasHeightForWidth())
        self.txtPort.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtPort.setFont(font)
        self.txtPort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtPort.setObjectName("txtPort")
        self.gridLayout_8.addWidget(self.txtPort, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_8.addWidget(self.label_40, 1, 0, 1, 1)
        self.btnConnect = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnConnect.setFont(font)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout_8.addWidget(self.btnConnect, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_8)
        self.lblServerMsg = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblServerMsg.setFont(font)
        self.lblServerMsg.setObjectName("lblServerMsg")
        self.verticalLayout_12.addWidget(self.lblServerMsg)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_23.addWidget(self.label_38)
        self.line_11 = QtWidgets.QFrame(self.tab_3)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_23.addWidget(self.line_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chkDanger = QtWidgets.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkDanger.setFont(font)
        self.chkDanger.setObjectName("chkDanger")
        self.horizontalLayout_3.addWidget(self.chkDanger)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.gbDanger = QtWidgets.QFrame(self.tab_3)
        self.gbDanger.setEnabled(False)
        self.gbDanger.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gbDanger.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gbDanger.setObjectName("gbDanger")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.gbDanger)
        self.verticalLayout_11.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_41 = QtWidgets.QLabel(self.gbDanger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_24.addWidget(self.label_41)
        self.line_12 = QtWidgets.QFrame(self.gbDanger)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_24.addWidget(self.line_12)
        self.verticalLayout_11.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lblScanComDelay = QtWidgets.QLabel(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblScanComDelay.setFont(font)
        self.lblScanComDelay.setObjectName("lblScanComDelay")
        self.horizontalLayout_20.addWidget(self.lblScanComDelay)
        self.txtScanComDelay = QtWidgets.QLineEdit(self.gbDanger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtScanComDelay.sizePolicy().hasHeightForWidth())
        self.txtScanComDelay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtScanComDelay.setFont(font)
        self.txtScanComDelay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtScanComDelay.setObjectName("txtScanComDelay")
        self.horizontalLayout_20.addWidget(self.txtScanComDelay)
        self.lblScanComDelayUnit = QtWidgets.QLabel(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblScanComDelayUnit.setFont(font)
        self.lblScanComDelayUnit.setObjectName("lblScanComDelayUnit")
        self.horizontalLayout_20.addWidget(self.lblScanComDelayUnit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_51 = QtWidgets.QLabel(self.gbDanger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_25.addWidget(self.label_51)
        self.line_13 = QtWidgets.QFrame(self.gbDanger)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_25.addWidget(self.line_13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btnVregTest = QtWidgets.QPushButton(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnVregTest.setFont(font)
        self.btnVregTest.setObjectName("btnVregTest")
        self.horizontalLayout_14.addWidget(self.btnVregTest)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(11, -1, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_23 = QtWidgets.QLabel(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 1, 0, 1, 1)
        self.txtVregMin = QtWidgets.QLineEdit(self.gbDanger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVregMin.sizePolicy().hasHeightForWidth())
        self.txtVregMin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVregMin.setFont(font)
        self.txtVregMin.setStyleSheet("")
        self.txtVregMin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtVregMin.setObjectName("txtVregMin")
        self.gridLayout_6.addWidget(self.txtVregMin, 0, 1, 1, 1)
        self.txtVregMax = QtWidgets.QLineEdit(self.gbDanger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVregMax.sizePolicy().hasHeightForWidth())
        self.txtVregMax.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVregMax.setFont(font)
        self.txtVregMax.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtVregMax.setObjectName("txtVregMax")
        self.gridLayout_6.addWidget(self.txtVregMax, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 1, 2, 1, 1)
        self.btnSetVregLimits = QtWidgets.QPushButton(self.gbDanger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetVregLimits.sizePolicy().hasHeightForWidth())
        self.btnSetVregLimits.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSetVregLimits.setFont(font)
        self.btnSetVregLimits.setObjectName("btnSetVregLimits")
        self.gridLayout_6.addWidget(self.btnSetVregLimits, 1, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 1, 3, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_6)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_53 = QtWidgets.QLabel(self.gbDanger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_26.addWidget(self.label_53)
        self.line_14 = QtWidgets.QFrame(self.gbDanger)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout_26.addWidget(self.line_14)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.rbVMove = QtWidgets.QRadioButton(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rbVMove.setFont(font)
        self.rbVMove.setChecked(True)
        self.rbVMove.setObjectName("rbVMove")
        self.horizontalLayout_13.addWidget(self.rbVMove)
        self.rbHMove = QtWidgets.QRadioButton(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rbHMove.setFont(font)
        self.rbHMove.setObjectName("rbHMove")
        self.horizontalLayout_13.addWidget(self.rbHMove)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.btnRetract = QtWidgets.QPushButton(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnRetract.setFont(font)
        self.btnRetract.setObjectName("btnRetract")
        self.horizontalLayout_27.addWidget(self.btnRetract)
        self.btnExtend = QtWidgets.QPushButton(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnExtend.setFont(font)
        self.btnExtend.setObjectName("btnExtend")
        self.horizontalLayout_27.addWidget(self.btnExtend)
        self.btnStop = QtWidgets.QPushButton(self.gbDanger)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnStop.setFont(font)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_27.addWidget(self.btnStop)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.verticalLayout_12.addWidget(self.gbDanger)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_59 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("::enabled {\n"
"color:#003399;\n"
"font-size:12pt;\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"font-size:12pt;\n"
"}")
        self.label_59.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_14.addWidget(self.label_59)
        self.label_60 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_14.addWidget(self.label_60)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_61 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_21.addWidget(self.label_61)
        self.line_18 = QtWidgets.QFrame(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_18.setFont(font)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_21.addWidget(self.line_18)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.rbVCalib = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rbVCalib.setFont(font)
        self.rbVCalib.setChecked(True)
        self.rbVCalib.setObjectName("rbVCalib")
        self.verticalLayout_14.addWidget(self.rbVCalib)
        self.gbVCalib = QtWidgets.QFrame(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gbVCalib.setFont(font)
        self.gbVCalib.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gbVCalib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gbVCalib.setObjectName("gbVCalib")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gbVCalib)
        self.verticalLayout_6.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtVCalibUpper = QtWidgets.QLineEdit(self.gbVCalib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVCalibUpper.sizePolicy().hasHeightForWidth())
        self.txtVCalibUpper.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVCalibUpper.setFont(font)
        self.txtVCalibUpper.setMaxLength(10)
        self.txtVCalibUpper.setObjectName("txtVCalibUpper")
        self.gridLayout_2.addWidget(self.txtVCalibUpper, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gbVCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.txtVCalibLower = QtWidgets.QLineEdit(self.gbVCalib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVCalibLower.sizePolicy().hasHeightForWidth())
        self.txtVCalibLower.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVCalibLower.setFont(font)
        self.txtVCalibLower.setMaxLength(10)
        self.txtVCalibLower.setObjectName("txtVCalibLower")
        self.gridLayout_2.addWidget(self.txtVCalibLower, 1, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gbVCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gbVCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 1, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gbVCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 0, 2, 1, 1)
        self.btnStartVCalib = QtWidgets.QPushButton(self.gbVCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnStartVCalib.setFont(font)
        self.btnStartVCalib.setObjectName("btnStartVCalib")
        self.gridLayout_2.addWidget(self.btnStartVCalib, 1, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.lblVCalibError = QtWidgets.QLabel(self.gbVCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblVCalibError.setFont(font)
        self.lblVCalibError.setWordWrap(True)
        self.lblVCalibError.setObjectName("lblVCalibError")
        self.verticalLayout_6.addWidget(self.lblVCalibError)
        self.verticalLayout_14.addWidget(self.gbVCalib)
        self.rbHCalib = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rbHCalib.setFont(font)
        self.rbHCalib.setObjectName("rbHCalib")
        self.verticalLayout_14.addWidget(self.rbHCalib)
        self.gbHCalib = QtWidgets.QFrame(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gbHCalib.setFont(font)
        self.gbHCalib.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gbHCalib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gbHCalib.setObjectName("gbHCalib")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbHCalib)
        self.verticalLayout_3.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.txtHCalibUpper = QtWidgets.QLineEdit(self.gbHCalib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHCalibUpper.sizePolicy().hasHeightForWidth())
        self.txtHCalibUpper.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtHCalibUpper.setFont(font)
        self.txtHCalibUpper.setMaxLength(10)
        self.txtHCalibUpper.setObjectName("txtHCalibUpper")
        self.gridLayout_7.addWidget(self.txtHCalibUpper, 0, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gbHCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_7.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gbHCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_7.addWidget(self.label_52, 1, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gbHCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_7.addWidget(self.label_49, 0, 2, 1, 1)
        self.txtHCalibLower = QtWidgets.QLineEdit(self.gbHCalib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHCalibLower.sizePolicy().hasHeightForWidth())
        self.txtHCalibLower.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtHCalibLower.setFont(font)
        self.txtHCalibLower.setMaxLength(10)
        self.txtHCalibLower.setObjectName("txtHCalibLower")
        self.gridLayout_7.addWidget(self.txtHCalibLower, 1, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gbHCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_7.addWidget(self.label_50, 1, 0, 1, 1)
        self.btnStartHCalib = QtWidgets.QPushButton(self.gbHCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnStartHCalib.setFont(font)
        self.btnStartHCalib.setObjectName("btnStartHCalib")
        self.gridLayout_7.addWidget(self.btnStartHCalib, 1, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem10, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.lblHCalibError = QtWidgets.QLabel(self.gbHCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblHCalibError.setFont(font)
        self.lblHCalibError.setWordWrap(True)
        self.lblHCalibError.setObjectName("lblHCalibError")
        self.verticalLayout_3.addWidget(self.lblHCalibError)
        self.verticalLayout_14.addWidget(self.gbHCalib)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_62 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_22.addWidget(self.label_62)
        self.line_19 = QtWidgets.QFrame(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_19.setFont(font)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.horizontalLayout_22.addWidget(self.line_19)
        self.verticalLayout_14.addLayout(self.horizontalLayout_22)
        self.gbVolCalib = QtWidgets.QFrame(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gbVolCalib.setFont(font)
        self.gbVolCalib.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gbVolCalib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gbVolCalib.setObjectName("gbVolCalib")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gbVolCalib)
        self.verticalLayout_9.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_18 = QtWidgets.QLabel(self.gbVolCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 0, 0, 1, 1)
        self.txtSetVreg = QtWidgets.QLineEdit(self.gbVolCalib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSetVreg.sizePolicy().hasHeightForWidth())
        self.txtSetVreg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtSetVreg.setFont(font)
        self.txtSetVreg.setMaxLength(10)
        self.txtSetVreg.setObjectName("txtSetVreg")
        self.gridLayout_9.addWidget(self.txtSetVreg, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gbVolCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 0, 2, 1, 1)
        self.txtVregCalib = QtWidgets.QLineEdit(self.gbVolCalib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVregCalib.sizePolicy().hasHeightForWidth())
        self.txtVregCalib.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVregCalib.setFont(font)
        self.txtVregCalib.setMaxLength(10)
        self.txtVregCalib.setObjectName("txtVregCalib")
        self.gridLayout_9.addWidget(self.txtVregCalib, 1, 1, 1, 1)
        self.btnAddVregPoint = QtWidgets.QPushButton(self.gbVolCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnAddVregPoint.setFont(font)
        self.btnAddVregPoint.setObjectName("btnAddVregPoint")
        self.gridLayout_9.addWidget(self.btnAddVregPoint, 1, 4, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gbVolCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_9.addWidget(self.label_55, 1, 0, 1, 1)
        self.btnSetVreg = QtWidgets.QPushButton(self.gbVolCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnSetVreg.setFont(font)
        self.btnSetVreg.setObjectName("btnSetVreg")
        self.gridLayout_9.addWidget(self.btnSetVreg, 0, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gbVolCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 1, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 0, 3, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_9)
        self.lblVolCalibError = QtWidgets.QLabel(self.gbVolCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblVolCalibError.setFont(font)
        self.lblVolCalibError.setObjectName("lblVolCalibError")
        self.verticalLayout_9.addWidget(self.lblVolCalibError)
        self.line_4 = QtWidgets.QFrame(self.gbVolCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_9.addWidget(self.line_4)
        self.label_58 = QtWidgets.QLabel(self.gbVolCalib)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_9.addWidget(self.label_58)
        self.verticalLayout_14.addWidget(self.gbVolCalib)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem12)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("::enabled {\n"
"color:#003399;\n"
"font-size:12pt;\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"font-size:12pt;\n"
"}")
        self.label_63.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_17.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_17.addWidget(self.label_64)
        self.splitScan = QtWidgets.QSplitter(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitScan.sizePolicy().hasHeightForWidth())
        self.splitScan.setSizePolicy(sizePolicy)
        self.splitScan.setAutoFillBackground(False)
        self.splitScan.setStyleSheet("")
        self.splitScan.setLineWidth(0)
        self.splitScan.setMidLineWidth(0)
        self.splitScan.setOrientation(QtCore.Qt.Horizontal)
        self.splitScan.setChildrenCollapsible(False)
        self.splitScan.setObjectName("splitScan")
        self.widget = QtWidgets.QWidget(self.splitScan)
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_65 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_28.addWidget(self.label_65)
        self.line_20 = QtWidgets.QFrame(self.widget)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.horizontalLayout_28.addWidget(self.line_20)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.gbFileOptions = QtWidgets.QFrame(self.widget)
        self.gbFileOptions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gbFileOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gbFileOptions.setObjectName("gbFileOptions")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.gbFileOptions)
        self.verticalLayout_18.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnChooseFile = QtWidgets.QPushButton(self.gbFileOptions)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnChooseFile.setFont(font)
        self.btnChooseFile.setObjectName("btnChooseFile")
        self.horizontalLayout_4.addWidget(self.btnChooseFile)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout_18.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addWidget(self.gbFileOptions)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_66 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_29.addWidget(self.label_66)
        self.line_21 = QtWidgets.QFrame(self.widget)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout_29.addWidget(self.line_21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.gbScanControls = QtWidgets.QFrame(self.widget)
        self.gbScanControls.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gbScanControls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gbScanControls.setObjectName("gbScanControls")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbScanControls)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rbVScan = QtWidgets.QRadioButton(self.gbScanControls)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rbVScan.setFont(font)
        self.rbVScan.setChecked(True)
        self.rbVScan.setObjectName("rbVScan")
        self.verticalLayout_4.addWidget(self.rbVScan)
        self.rbHScan = QtWidgets.QRadioButton(self.gbScanControls)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rbHScan.setFont(font)
        self.rbHScan.setObjectName("rbHScan")
        self.verticalLayout_4.addWidget(self.rbHScan)
        self.rbBothScan = QtWidgets.QRadioButton(self.gbScanControls)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rbBothScan.setFont(font)
        self.rbBothScan.setObjectName("rbBothScan")
        self.verticalLayout_4.addWidget(self.rbBothScan)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.gbScanControls)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.gbVScan = QtWidgets.QFrame(self.gbScanControls)
        self.gbVScan.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gbVScan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gbVScan.setObjectName("gbVScan")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbVScan)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtVMinPos = QtWidgets.QLineEdit(self.gbVScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVMinPos.sizePolicy().hasHeightForWidth())
        self.txtVMinPos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVMinPos.setFont(font)
        self.txtVMinPos.setText("")
        self.txtVMinPos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtVMinPos.setObjectName("txtVMinPos")
        self.gridLayout_3.addWidget(self.txtVMinPos, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtVMaxPos = QtWidgets.QLineEdit(self.gbVScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVMaxPos.sizePolicy().hasHeightForWidth())
        self.txtVMaxPos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVMaxPos.setFont(font)
        self.txtVMaxPos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtVMaxPos.setObjectName("txtVMaxPos")
        self.gridLayout_3.addWidget(self.txtVMaxPos, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtVStepPos = QtWidgets.QLineEdit(self.gbVScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVStepPos.sizePolicy().hasHeightForWidth())
        self.txtVStepPos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVStepPos.setFont(font)
        self.txtVStepPos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtVStepPos.setObjectName("txtVStepPos")
        self.gridLayout_3.addWidget(self.txtVStepPos, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.label_6 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.txtVMaxV = QtWidgets.QLineEdit(self.gbVScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVMaxV.sizePolicy().hasHeightForWidth())
        self.txtVMaxV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVMaxV.setFont(font)
        self.txtVMaxV.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtVMaxV.setObjectName("txtVMaxV")
        self.gridLayout.addWidget(self.txtVMaxV, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.txtVStepV = QtWidgets.QLineEdit(self.gbVScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVStepV.sizePolicy().hasHeightForWidth())
        self.txtVStepV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVStepV.setFont(font)
        self.txtVStepV.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtVStepV.setObjectName("txtVStepV")
        self.gridLayout.addWidget(self.txtVStepV, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.txtVMinV = QtWidgets.QLineEdit(self.gbVScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVMinV.sizePolicy().hasHeightForWidth())
        self.txtVMinV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtVMinV.setFont(font)
        self.txtVMinV.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtVMinV.setObjectName("txtVMinV")
        self.gridLayout.addWidget(self.txtVMinV, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 3, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 1, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.lblVScanError = QtWidgets.QLabel(self.gbVScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblVScanError.setFont(font)
        self.lblVScanError.setWordWrap(True)
        self.lblVScanError.setObjectName("lblVScanError")
        self.verticalLayout_2.addWidget(self.lblVScanError)
        self.verticalLayout_2.setStretch(4, 1)
        self.horizontalLayout.addWidget(self.gbVScan)
        self.line = QtWidgets.QFrame(self.gbScanControls)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gbHScan = QtWidgets.QFrame(self.gbScanControls)
        self.gbHScan.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gbHScan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gbHScan.setObjectName("gbHScan")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbHScan)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txtHMinPos = QtWidgets.QLineEdit(self.gbHScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHMinPos.sizePolicy().hasHeightForWidth())
        self.txtHMinPos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtHMinPos.setFont(font)
        self.txtHMinPos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtHMinPos.setObjectName("txtHMinPos")
        self.gridLayout_4.addWidget(self.txtHMinPos, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.txtHMaxPos = QtWidgets.QLineEdit(self.gbHScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHMaxPos.sizePolicy().hasHeightForWidth())
        self.txtHMaxPos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtHMaxPos.setFont(font)
        self.txtHMaxPos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtHMaxPos.setObjectName("txtHMaxPos")
        self.gridLayout_4.addWidget(self.txtHMaxPos, 1, 1, 1, 1)
        self.txtHStepPos = QtWidgets.QLineEdit(self.gbHScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHStepPos.sizePolicy().hasHeightForWidth())
        self.txtHStepPos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtHStepPos.setFont(font)
        self.txtHStepPos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtHStepPos.setObjectName("txtHStepPos")
        self.gridLayout_4.addWidget(self.txtHStepPos, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.label_14 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txtHMaxV = QtWidgets.QLineEdit(self.gbHScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHMaxV.sizePolicy().hasHeightForWidth())
        self.txtHMaxV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtHMaxV.setFont(font)
        self.txtHMaxV.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtHMaxV.setObjectName("txtHMaxV")
        self.gridLayout_5.addWidget(self.txtHMaxV, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.txtHMinV = QtWidgets.QLineEdit(self.gbHScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHMinV.sizePolicy().hasHeightForWidth())
        self.txtHMinV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtHMinV.setFont(font)
        self.txtHMinV.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtHMinV.setObjectName("txtHMinV")
        self.gridLayout_5.addWidget(self.txtHMinV, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 2, 0, 1, 1)
        self.txtHStepV = QtWidgets.QLineEdit(self.gbHScan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHStepV.sizePolicy().hasHeightForWidth())
        self.txtHStepV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtHStepV.setFont(font)
        self.txtHStepV.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtHStepV.setObjectName("txtHStepV")
        self.gridLayout_5.addWidget(self.txtHStepV, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 0, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 1, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.lblHScanError = QtWidgets.QLabel(self.gbHScan)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblHScanError.setFont(font)
        self.lblHScanError.setWordWrap(True)
        self.lblHScanError.setObjectName("lblHScanError")
        self.verticalLayout.addWidget(self.lblHScanError)
        self.verticalLayout.setStretch(4, 1)
        self.horizontalLayout.addWidget(self.gbHScan)
        self.verticalLayout_8.addWidget(self.gbScanControls)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_67 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_30.addWidget(self.label_67)
        self.line_22 = QtWidgets.QFrame(self.widget)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.horizontalLayout_30.addWidget(self.line_22)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(11, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblScanPoints = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setItalic(False)
        self.lblScanPoints.setFont(font)
        self.lblScanPoints.setObjectName("lblScanPoints")
        self.verticalLayout_7.addWidget(self.lblScanPoints)
        self.lblSaveFile = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setItalic(False)
        self.lblSaveFile.setFont(font)
        self.lblSaveFile.setWordWrap(True)
        self.lblSaveFile.setObjectName("lblSaveFile")
        self.verticalLayout_7.addWidget(self.lblSaveFile)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnStartScan = QtWidgets.QPushButton(self.frame)
        self.btnStartScan.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnStartScan.setFont(font)
        self.btnStartScan.setObjectName("btnStartScan")
        self.horizontalLayout_2.addWidget(self.btnStartScan)
        self.btnStopScan = QtWidgets.QPushButton(self.frame)
        self.btnStopScan.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnStopScan.setFont(font)
        self.btnStopScan.setObjectName("btnStopScan")
        self.horizontalLayout_2.addWidget(self.btnStopScan)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addWidget(self.frame)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem16)
        self.widget1 = QtWidgets.QWidget(self.splitScan)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_68 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_31.addWidget(self.label_68)
        self.line_23 = QtWidgets.QFrame(self.widget1)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_31.addWidget(self.line_23)
        self.verticalLayout_16.addLayout(self.horizontalLayout_31)
        self.splitScanInfo = QtWidgets.QSplitter(self.widget1)
        self.splitScanInfo.setOrientation(QtCore.Qt.Vertical)
        self.splitScanInfo.setChildrenCollapsible(False)
        self.splitScanInfo.setObjectName("splitScanInfo")
        self.frame_3 = QtWidgets.QFrame(self.splitScanInfo)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_15.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.rbVScanStatus = QtWidgets.QRadioButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rbVScanStatus.setFont(font)
        self.rbVScanStatus.setStyleSheet("font-weight: bold")
        self.rbVScanStatus.setChecked(True)
        self.rbVScanStatus.setObjectName("rbVScanStatus")
        self.horizontalLayout_19.addWidget(self.rbVScanStatus)
        self.rbHScanStatus = QtWidgets.QRadioButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rbHScanStatus.setFont(font)
        self.rbHScanStatus.setStyleSheet("font-weight: bold")
        self.rbHScanStatus.setObjectName("rbHScanStatus")
        self.horizontalLayout_19.addWidget(self.rbHScanStatus)
        self.verticalLayout_15.addLayout(self.horizontalLayout_19)
        self.lyGrad = QtWidgets.QVBoxLayout()
        self.lyGrad.setObjectName("lyGrad")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lyScan = QtWidgets.QHBoxLayout()
        self.lyScan.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.lyScan.setObjectName("lyScan")
        self.label_43 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_43.setObjectName("label_43")
        self.lyScan.addWidget(self.label_43)
        self.lblScanStatus = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScanStatus.sizePolicy().hasHeightForWidth())
        self.lblScanStatus.setSizePolicy(sizePolicy)
        self.lblScanStatus.setMinimumSize(QtCore.QSize(0, 0))
        self.lblScanStatus.setFrameShape(QtWidgets.QFrame.Box)
        self.lblScanStatus.setText("")
        self.lblScanStatus.setObjectName("lblScanStatus")
        self.lyScan.addWidget(self.lblScanStatus)
        self.verticalLayout_10.addLayout(self.lyScan)
        self.label_44 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_10.addWidget(self.label_44)
        self.lyGrad.addLayout(self.verticalLayout_10)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lyGrad.addWidget(self.line_3)
        self.lblColorScale = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblColorScale.sizePolicy().hasHeightForWidth())
        self.lblColorScale.setSizePolicy(sizePolicy)
        self.lblColorScale.setMinimumSize(QtCore.QSize(0, 15))
        self.lblColorScale.setMaximumSize(QtCore.QSize(16777215, 15))
        self.lblColorScale.setFrameShape(QtWidgets.QFrame.Box)
        self.lblColorScale.setText("")
        self.lblColorScale.setObjectName("lblColorScale")
        self.lyGrad.addWidget(self.lblColorScale)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblColorScaleMin = QtWidgets.QLabel(self.frame_3)
        self.lblColorScaleMin.setObjectName("lblColorScaleMin")
        self.horizontalLayout_9.addWidget(self.lblColorScaleMin)
        self.lblColorScaleMid = QtWidgets.QLabel(self.frame_3)
        self.lblColorScaleMid.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColorScaleMid.setObjectName("lblColorScaleMid")
        self.horizontalLayout_9.addWidget(self.lblColorScaleMid)
        self.lblColorScaleMax = QtWidgets.QLabel(self.frame_3)
        self.lblColorScaleMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblColorScaleMax.setObjectName("lblColorScaleMax")
        self.horizontalLayout_9.addWidget(self.lblColorScaleMax)
        self.lyGrad.addLayout(self.horizontalLayout_9)
        self.verticalLayout_15.addLayout(self.lyGrad)
        self.frame_2 = QtWidgets.QFrame(self.splitScanInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_13.setContentsMargins(-1, 5, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lblScanProgress = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblScanProgress.setFont(font)
        self.lblScanProgress.setObjectName("lblScanProgress")
        self.verticalLayout_13.addWidget(self.lblScanProgress)
        self.lblScanTime = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblScanTime.setFont(font)
        self.lblScanTime.setObjectName("lblScanTime")
        self.verticalLayout_13.addWidget(self.lblScanTime)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem17)
        self.verticalLayout_16.addWidget(self.splitScanInfo)
        self.verticalLayout_17.addWidget(self.splitScan)
        self.verticalLayout_17.setStretch(2, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1154, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.btnSaveSession = QtWidgets.QAction(MainWindow)
        self.btnSaveSession.setObjectName("btnSaveSession")
        self.btnLoadSession = QtWidgets.QAction(MainWindow)
        self.btnLoadSession.setObjectName("btnLoadSession")
        self.btnExit = QtWidgets.QAction(MainWindow)
        self.btnExit.setObjectName("btnExit")
        self.menuFile.addAction(self.btnSaveSession)
        self.menuFile.addAction(self.btnLoadSession)
        self.menuFile.addAction(self.btnExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.txtIP)
        MainWindow.setTabOrder(self.txtIP, self.txtPort)
        MainWindow.setTabOrder(self.txtPort, self.rbVScan)
        MainWindow.setTabOrder(self.rbVScan, self.rbHScan)
        MainWindow.setTabOrder(self.rbHScan, self.rbBothScan)
        MainWindow.setTabOrder(self.rbBothScan, self.txtVMinPos)
        MainWindow.setTabOrder(self.txtVMinPos, self.txtVMaxPos)
        MainWindow.setTabOrder(self.txtVMaxPos, self.txtVStepPos)
        MainWindow.setTabOrder(self.txtVStepPos, self.txtVMinV)
        MainWindow.setTabOrder(self.txtVMinV, self.txtVMaxV)
        MainWindow.setTabOrder(self.txtVMaxV, self.txtVStepV)
        MainWindow.setTabOrder(self.txtVStepV, self.txtHMinPos)
        MainWindow.setTabOrder(self.txtHMinPos, self.txtHMaxPos)
        MainWindow.setTabOrder(self.txtHMaxPos, self.txtHStepPos)
        MainWindow.setTabOrder(self.txtHStepPos, self.txtHMinV)
        MainWindow.setTabOrder(self.txtHMinV, self.txtHMaxV)
        MainWindow.setTabOrder(self.txtHMaxV, self.txtHStepV)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_56.setText(_translate("MainWindow", "Device Status"))
        self.lblVerPos.setText(_translate("MainWindow", "Vertical: -- (Not calibrated)"))
        self.lblHorPos.setText(_translate("MainWindow", "Horizontal: -- (Not calibrated)"))
        self.lblV.setText(_translate("MainWindow", "Voltage: --"))
        self.lblCur.setText(_translate("MainWindow", "Current: --"))
        self.label_57.setText(_translate("MainWindow", "Server Status"))
        self.lblServerStatus.setText(_translate("MainWindow", "Not connected"))
        self.lblPollRate.setText(_translate("MainWindow", "Polling rate: --"))
        self.label_42.setText(_translate("MainWindow", "Connect to Server"))
        self.label_54.setText(_translate("MainWindow", "Enter the IP and port for the server."))
        self.label_25.setText(_translate("MainWindow", "Server"))
        self.label_39.setText(_translate("MainWindow", "IP:"))
        self.txtIP.setText(_translate("MainWindow", "10.77.0.4"))
        self.txtPort.setText(_translate("MainWindow", "5000"))
        self.label_40.setText(_translate("MainWindow", "Port:"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.lblServerMsg.setText(_translate("MainWindow", "TextLabel"))
        self.label_38.setText(_translate("MainWindow", "Danger Zone"))
        self.chkDanger.setText(_translate("MainWindow", "I know what I\'m doing"))
        self.label_41.setText(_translate("MainWindow", "Communication"))
        self.lblScanComDelay.setText(_translate("MainWindow", "COM Delay:"))
        self.txtScanComDelay.setText(_translate("MainWindow", "0.5"))
        self.lblScanComDelayUnit.setText(_translate("MainWindow", "seconds"))
        self.label_51.setText(_translate("MainWindow", "Voltage Regulator"))
        self.btnVregTest.setText(_translate("MainWindow", "Send random value [-1, 1]"))
        self.label_23.setText(_translate("MainWindow", "kV"))
        self.label_21.setText(_translate("MainWindow", "Min HV output"))
        self.label_22.setText(_translate("MainWindow", "Max HV output"))
        self.txtVregMin.setText(_translate("MainWindow", "-1.5"))
        self.txtVregMax.setText(_translate("MainWindow", "1.5"))
        self.label_24.setText(_translate("MainWindow", "kV"))
        self.btnSetVregLimits.setText(_translate("MainWindow", "Set"))
        self.label_53.setText(_translate("MainWindow", "Stepper Motors"))
        self.rbVMove.setText(_translate("MainWindow", "Vertical"))
        self.rbHMove.setText(_translate("MainWindow", "Horizontal"))
        self.btnRetract.setText(_translate("MainWindow", "Retract"))
        self.btnExtend.setText(_translate("MainWindow", "Extend"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Communication"))
        self.label_59.setText(_translate("MainWindow", "Calibrate Devices"))
        self.label_60.setText(_translate("MainWindow", "The voltage regulator and at least one stepper motor must be calibrated before performing a scan."))
        self.label_61.setText(_translate("MainWindow", "Stepper Motors"))
        self.rbVCalib.setText(_translate("MainWindow", "Vertical"))
        self.label.setText(_translate("MainWindow", "Upper:"))
        self.label_47.setText(_translate("MainWindow", "Lower:"))
        self.label_46.setText(_translate("MainWindow", "mm"))
        self.label_45.setText(_translate("MainWindow", "mm"))
        self.btnStartVCalib.setText(_translate("MainWindow", "Start Calibration"))
        self.lblVCalibError.setText(_translate("MainWindow", "<html><head/><body><p>TextLabel</p></body></html>"))
        self.rbHCalib.setText(_translate("MainWindow", "Horizontal"))
        self.label_48.setText(_translate("MainWindow", "Upper:"))
        self.label_52.setText(_translate("MainWindow", "mm"))
        self.label_49.setText(_translate("MainWindow", "mm"))
        self.label_50.setText(_translate("MainWindow", "Lower:"))
        self.btnStartHCalib.setText(_translate("MainWindow", "Start Calibration"))
        self.lblHCalibError.setText(_translate("MainWindow", "<html><head/><body><p>TextLabel</p></body></html>"))
        self.label_62.setText(_translate("MainWindow", "Voltage Regulator"))
        self.label_18.setText(_translate("MainWindow", "Set voltage:"))
        self.label_19.setText(_translate("MainWindow", "V"))
        self.btnAddVregPoint.setText(_translate("MainWindow", "Add Point"))
        self.label_55.setText(_translate("MainWindow", "Measured output:"))
        self.btnSetVreg.setText(_translate("MainWindow", "Set"))
        self.label_20.setText(_translate("MainWindow", "kV"))
        self.lblVolCalibError.setText(_translate("MainWindow", "TextLabel"))
        self.label_58.setText(_translate("MainWindow", "Calibration points"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calibration"))
        self.label_63.setText(_translate("MainWindow", "Configure Scan"))
        self.label_64.setText(_translate("MainWindow", "Choose an output file and specify scan points."))
        self.label_65.setText(_translate("MainWindow", "File Options"))
        self.btnChooseFile.setText(_translate("MainWindow", "Choose Output File"))
        self.label_66.setText(_translate("MainWindow", "Scan Points"))
        self.rbVScan.setText(_translate("MainWindow", "Vertical"))
        self.rbHScan.setText(_translate("MainWindow", "Horizontal"))
        self.rbBothScan.setText(_translate("MainWindow", "Both"))
        self.label_5.setText(_translate("MainWindow", "Vertical"))
        self.label_2.setText(_translate("MainWindow", "Min:"))
        self.label_26.setText(_translate("MainWindow", "mm"))
        self.label_3.setText(_translate("MainWindow", "Max:"))
        self.label_27.setText(_translate("MainWindow", "mm"))
        self.label_4.setText(_translate("MainWindow", "Step:"))
        self.label_28.setText(_translate("MainWindow", "mm"))
        self.label_6.setText(_translate("MainWindow", "Voltage"))
        self.label_7.setText(_translate("MainWindow", "Min:"))
        self.label_9.setText(_translate("MainWindow", "Step:"))
        self.label_8.setText(_translate("MainWindow", "Max:"))
        self.label_34.setText(_translate("MainWindow", "kV"))
        self.label_32.setText(_translate("MainWindow", "kV"))
        self.label_33.setText(_translate("MainWindow", "kV"))
        self.lblVScanError.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Horizontal"))
        self.label_11.setText(_translate("MainWindow", "Min:"))
        self.label_12.setText(_translate("MainWindow", "Max:"))
        self.label_13.setText(_translate("MainWindow", "Step:"))
        self.label_29.setText(_translate("MainWindow", "mm"))
        self.label_30.setText(_translate("MainWindow", "mm"))
        self.label_31.setText(_translate("MainWindow", "mm"))
        self.label_14.setText(_translate("MainWindow", "Voltage"))
        self.label_16.setText(_translate("MainWindow", "Max:"))
        self.label_15.setText(_translate("MainWindow", "Min:"))
        self.label_17.setText(_translate("MainWindow", "Step:"))
        self.label_35.setText(_translate("MainWindow", "kV"))
        self.label_36.setText(_translate("MainWindow", "kV"))
        self.label_37.setText(_translate("MainWindow", "kV"))
        self.lblHScanError.setText(_translate("MainWindow", "TextLabel"))
        self.label_67.setText(_translate("MainWindow", "Scan Summary"))
        self.lblScanPoints.setText(_translate("MainWindow", "Total points: --"))
        self.lblSaveFile.setText(_translate("MainWindow", "Output file not set"))
        self.btnStartScan.setText(_translate("MainWindow", "Start Scan"))
        self.btnStopScan.setText(_translate("MainWindow", "Stop Scan"))
        self.label_68.setText(_translate("MainWindow", "Scan Status"))
        self.rbVScanStatus.setText(_translate("MainWindow", "Vertical"))
        self.rbHScanStatus.setText(_translate("MainWindow", "Horizontal"))
        self.label_43.setText(_translate("MainWindow", "V"))
        self.label_44.setText(_translate("MainWindow", "mm"))
        self.lblColorScaleMin.setText(_translate("MainWindow", "--"))
        self.lblColorScaleMid.setText(_translate("MainWindow", "--"))
        self.lblColorScaleMax.setText(_translate("MainWindow", "--"))
        self.lblScanProgress.setText(_translate("MainWindow", "Current: 500/1000 (50%)"))
        self.lblScanTime.setText(_translate("MainWindow", "Est. Time Remaining: 5 minutes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scan"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.btnSaveSession.setText(_translate("MainWindow", "Save Session"))
        self.btnLoadSession.setText(_translate("MainWindow", "Load Session"))
        self.btnExit.setText(_translate("MainWindow", "&Exit"))

