# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1154, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblGraphic = QtWidgets.QLabel(self.centralwidget)
        self.lblGraphic.setMinimumSize(QtCore.QSize(300, 300))
        self.lblGraphic.setFrameShape(QtWidgets.QFrame.Box)
        self.lblGraphic.setText("")
        self.lblGraphic.setPixmap(QtGui.QPixmap("../../Ion-Source-Control-System/Software/example.png"))
        self.lblGraphic.setObjectName("lblGraphic")
        self.verticalLayout_6.addWidget(self.lblGraphic)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblVerPos = QtWidgets.QLabel(self.groupBox_5)
        self.lblVerPos.setObjectName("lblVerPos")
        self.verticalLayout_5.addWidget(self.lblVerPos)
        self.lblHorPos = QtWidgets.QLabel(self.groupBox_5)
        self.lblHorPos.setObjectName("lblHorPos")
        self.verticalLayout_5.addWidget(self.lblHorPos)
        self.lblV = QtWidgets.QLabel(self.groupBox_5)
        self.lblV.setObjectName("lblV")
        self.verticalLayout_5.addWidget(self.lblV)
        self.lblCur = QtWidgets.QLabel(self.groupBox_5)
        self.lblCur.setObjectName("lblCur")
        self.verticalLayout_5.addWidget(self.lblCur)
        self.line_4 = QtWidgets.QFrame(self.groupBox_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.lblPollRate = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.lblPollRate.setFont(font)
        self.lblPollRate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPollRate.setObjectName("lblPollRate")
        self.verticalLayout_5.addWidget(self.lblPollRate)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_39 = QtWidgets.QLabel(self.groupBox_11)
        self.label_39.setObjectName("label_39")
        self.gridLayout_9.addWidget(self.label_39, 0, 0, 1, 1)
        self.txtIP = QtWidgets.QLineEdit(self.groupBox_11)
        self.txtIP.setInputMask("")
        self.txtIP.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIP.setObjectName("txtIP")
        self.gridLayout_9.addWidget(self.txtIP, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_11)
        self.label_40.setObjectName("label_40")
        self.gridLayout_9.addWidget(self.label_40, 1, 0, 1, 1)
        self.txtPort = QtWidgets.QLineEdit(self.groupBox_11)
        self.txtPort.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPort.setObjectName("txtPort")
        self.gridLayout_9.addWidget(self.txtPort, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.btnConnect = QtWidgets.QPushButton(self.groupBox_11)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_11.addWidget(self.btnConnect)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.lblServerMsg = QtWidgets.QLabel(self.groupBox_11)
        self.lblServerMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.lblServerMsg.setObjectName("lblServerMsg")
        self.verticalLayout_11.addWidget(self.lblServerMsg)
        self.horizontalLayout_12.addLayout(self.verticalLayout_11)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_18.addWidget(self.groupBox_11)
        self.line_6 = QtWidgets.QFrame(self.tab_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_18.addWidget(self.line_6)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lblVerPos_2 = QtWidgets.QLabel(self.groupBox_3)
        self.lblVerPos_2.setObjectName("lblVerPos_2")
        self.verticalLayout_12.addWidget(self.lblVerPos_2)
        self.line_7 = QtWidgets.QFrame(self.groupBox_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_12.addWidget(self.line_7)
        self.label_57 = QtWidgets.QLabel(self.groupBox_3)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_12.addWidget(self.label_57)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_13.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_13.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_13.addWidget(self.radioButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_12.addWidget(self.label_42)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_14.addWidget(self.lineEdit)
        self.label_56 = QtWidgets.QLabel(self.groupBox_3)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_14.addWidget(self.label_56)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_17.addWidget(self.groupBox_3)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lblVerPos_4 = QtWidgets.QLabel(self.groupBox_10)
        self.lblVerPos_4.setObjectName("lblVerPos_4")
        self.gridLayout_12.addWidget(self.lblVerPos_4, 0, 0, 1, 1)
        self.btnVregTest = QtWidgets.QPushButton(self.groupBox_10)
        self.btnVregTest.setObjectName("btnVregTest")
        self.gridLayout_12.addWidget(self.btnVregTest, 1, 0, 1, 1)
        self.lblVerPos_8 = QtWidgets.QLabel(self.groupBox_10)
        self.lblVerPos_8.setObjectName("lblVerPos_8")
        self.gridLayout_12.addWidget(self.lblVerPos_8, 2, 0, 1, 1)
        self.horizontalLayout_17.addWidget(self.groupBox_10)
        self.verticalLayout_18.addLayout(self.horizontalLayout_17)
        self.gbSteppers = QtWidgets.QGroupBox(self.tab_3)
        self.gbSteppers.setObjectName("gbSteppers")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.gbSteppers)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem5 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.rbVMove = QtWidgets.QRadioButton(self.gbSteppers)
        self.rbVMove.setChecked(True)
        self.rbVMove.setObjectName("rbVMove")
        self.gridLayout_6.addWidget(self.rbVMove, 0, 0, 1, 1)
        self.btnRetract = QtWidgets.QPushButton(self.gbSteppers)
        self.btnRetract.setObjectName("btnRetract")
        self.gridLayout_6.addWidget(self.btnRetract, 1, 0, 1, 1)
        self.rbHMove = QtWidgets.QRadioButton(self.gbSteppers)
        self.rbHMove.setObjectName("rbHMove")
        self.gridLayout_6.addWidget(self.rbHMove, 0, 1, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.gbSteppers)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout_6.addWidget(self.btnStop, 2, 0, 1, 2)
        self.btnExtend = QtWidgets.QPushButton(self.gbSteppers)
        self.btnExtend.setObjectName("btnExtend")
        self.gridLayout_6.addWidget(self.btnExtend, 1, 1, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.verticalLayout_18.addWidget(self.gbSteppers)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_19.addWidget(self.line_9)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.gbStepperCalib = QtWidgets.QGroupBox(self.tab)
        self.gbStepperCalib.setObjectName("gbStepperCalib")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.gbStepperCalib)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_55 = QtWidgets.QLabel(self.gbStepperCalib)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setItalic(True)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_14.addWidget(self.label_55)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.rbVCalib = QtWidgets.QRadioButton(self.gbStepperCalib)
        self.rbVCalib.setChecked(True)
        self.rbVCalib.setObjectName("rbVCalib")
        self.horizontalLayout.addWidget(self.rbVCalib)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.rbHCalib = QtWidgets.QRadioButton(self.gbStepperCalib)
        self.rbHCalib.setObjectName("rbHCalib")
        self.horizontalLayout.addWidget(self.rbHCalib)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout_14.addLayout(self.horizontalLayout)
        self.line_16 = QtWidgets.QFrame(self.gbStepperCalib)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_14.addWidget(self.line_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gbVCalib = QtWidgets.QGroupBox(self.gbStepperCalib)
        self.gbVCalib.setEnabled(True)
        self.gbVCalib.setObjectName("gbVCalib")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbVCalib)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gbVCalib)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.txtVCalibUpper = QtWidgets.QLineEdit(self.gbVCalib)
        self.txtVCalibUpper.setMaxLength(10)
        self.txtVCalibUpper.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVCalibUpper.setObjectName("txtVCalibUpper")
        self.gridLayout_2.addWidget(self.txtVCalibUpper, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gbVCalib)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 0, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gbVCalib)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 1, 0, 1, 1)
        self.txtVCalibLower = QtWidgets.QLineEdit(self.gbVCalib)
        self.txtVCalibLower.setMaxLength(10)
        self.txtVCalibLower.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVCalibLower.setObjectName("txtVCalibLower")
        self.gridLayout_2.addWidget(self.txtVCalibLower, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gbVCalib)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.btnStartVCalib = QtWidgets.QPushButton(self.gbVCalib)
        self.btnStartVCalib.setObjectName("btnStartVCalib")
        self.verticalLayout_3.addWidget(self.btnStartVCalib)
        self.lblVCalibError = QtWidgets.QLabel(self.gbVCalib)
        self.lblVCalibError.setWordWrap(True)
        self.lblVCalibError.setObjectName("lblVCalibError")
        self.verticalLayout_3.addWidget(self.lblVCalibError)
        self.horizontalLayout_15.addWidget(self.gbVCalib)
        self.gbHCalib = QtWidgets.QGroupBox(self.gbStepperCalib)
        self.gbHCalib.setEnabled(True)
        self.gbHCalib.setObjectName("gbHCalib")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gbHCalib)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_48 = QtWidgets.QLabel(self.gbHCalib)
        self.label_48.setObjectName("label_48")
        self.gridLayout_7.addWidget(self.label_48, 0, 0, 1, 1)
        self.txtHCalibUpper = QtWidgets.QLineEdit(self.gbHCalib)
        self.txtHCalibUpper.setMaxLength(10)
        self.txtHCalibUpper.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHCalibUpper.setObjectName("txtHCalibUpper")
        self.gridLayout_7.addWidget(self.txtHCalibUpper, 0, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gbHCalib)
        self.label_49.setObjectName("label_49")
        self.gridLayout_7.addWidget(self.label_49, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gbHCalib)
        self.label_50.setObjectName("label_50")
        self.gridLayout_7.addWidget(self.label_50, 1, 0, 1, 1)
        self.txtHCalibLower = QtWidgets.QLineEdit(self.gbHCalib)
        self.txtHCalibLower.setMaxLength(10)
        self.txtHCalibLower.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHCalibLower.setObjectName("txtHCalibLower")
        self.gridLayout_7.addWidget(self.txtHCalibLower, 1, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gbHCalib)
        self.label_52.setObjectName("label_52")
        self.gridLayout_7.addWidget(self.label_52, 1, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_7)
        self.btnStartHCalib = QtWidgets.QPushButton(self.gbHCalib)
        self.btnStartHCalib.setObjectName("btnStartHCalib")
        self.verticalLayout_9.addWidget(self.btnStartHCalib)
        self.lblHCalibError = QtWidgets.QLabel(self.gbHCalib)
        self.lblHCalibError.setWordWrap(True)
        self.lblHCalibError.setObjectName("lblHCalibError")
        self.verticalLayout_9.addWidget(self.lblHCalibError)
        self.horizontalLayout_15.addWidget(self.gbHCalib)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem10)
        self.horizontalLayout_16.addWidget(self.gbStepperCalib)
        self.gbVolCalib = QtWidgets.QGroupBox(self.tab)
        self.gbVolCalib.setEnabled(True)
        self.gbVolCalib.setObjectName("gbVolCalib")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.gbVolCalib)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_58 = QtWidgets.QLabel(self.gbVolCalib)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setItalic(True)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setWordWrap(True)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_17.addWidget(self.label_58)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtSetVreg = QtWidgets.QLineEdit(self.gbVolCalib)
        self.txtSetVreg.setMaxLength(10)
        self.txtSetVreg.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSetVreg.setObjectName("txtSetVreg")
        self.horizontalLayout_4.addWidget(self.txtSetVreg)
        self.label_19 = QtWidgets.QLabel(self.gbVolCalib)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.btnSetVreg = QtWidgets.QPushButton(self.gbVolCalib)
        self.btnSetVreg.setObjectName("btnSetVreg")
        self.horizontalLayout_4.addWidget(self.btnSetVreg)
        self.verticalLayout_17.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.txtVregCalib = QtWidgets.QLineEdit(self.gbVolCalib)
        self.txtVregCalib.setMaxLength(10)
        self.txtVregCalib.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVregCalib.setObjectName("txtVregCalib")
        self.horizontalLayout_7.addWidget(self.txtVregCalib)
        self.label_20 = QtWidgets.QLabel(self.gbVolCalib)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.verticalLayout_17.addLayout(self.horizontalLayout_7)
        self.lblVolCalibError = QtWidgets.QLabel(self.gbVolCalib)
        self.lblVolCalibError.setWordWrap(True)
        self.lblVolCalibError.setObjectName("lblVolCalibError")
        self.verticalLayout_17.addWidget(self.lblVolCalibError)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.btnAddVregPoint = QtWidgets.QPushButton(self.gbVolCalib)
        self.btnAddVregPoint.setObjectName("btnAddVregPoint")
        self.horizontalLayout_10.addWidget(self.btnAddVregPoint)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        self.line_8 = QtWidgets.QFrame(self.gbVolCalib)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_17.addWidget(self.line_8)
        spacerItem13 = QtWidgets.QSpacerItem(20, 435, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem13)
        self.horizontalLayout_16.addWidget(self.gbVolCalib)
        self.verticalLayout_19.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.splitScan = QtWidgets.QSplitter(self.tab_2)
        self.splitScan.setOrientation(QtCore.Qt.Horizontal)
        self.splitScan.setChildrenCollapsible(False)
        self.splitScan.setObjectName("splitScan")
        self.layoutWidget = QtWidgets.QWidget(self.splitScan)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gbFileOptions = QtWidgets.QGroupBox(self.layoutWidget)
        self.gbFileOptions.setObjectName("gbFileOptions")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gbFileOptions)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.btnChooseFile = QtWidgets.QPushButton(self.gbFileOptions)
        self.btnChooseFile.setObjectName("btnChooseFile")
        self.horizontalLayout_6.addWidget(self.btnChooseFile)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addWidget(self.gbFileOptions)
        self.gbScanControls = QtWidgets.QGroupBox(self.layoutWidget)
        self.gbScanControls.setObjectName("gbScanControls")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbScanControls)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rbVScan = QtWidgets.QRadioButton(self.gbScanControls)
        self.rbVScan.setChecked(True)
        self.rbVScan.setObjectName("rbVScan")
        self.horizontalLayout_8.addWidget(self.rbVScan)
        self.rbHScan = QtWidgets.QRadioButton(self.gbScanControls)
        self.rbHScan.setObjectName("rbHScan")
        self.horizontalLayout_8.addWidget(self.rbHScan)
        self.rbBothScan = QtWidgets.QRadioButton(self.gbScanControls)
        self.rbBothScan.setObjectName("rbBothScan")
        self.horizontalLayout_8.addWidget(self.rbBothScan)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem16)
        self.lblScanComDelay = QtWidgets.QLabel(self.gbScanControls)
        self.lblScanComDelay.setObjectName("lblScanComDelay")
        self.horizontalLayout_20.addWidget(self.lblScanComDelay)
        self.txtScanComDelay = QtWidgets.QLineEdit(self.gbScanControls)
        self.txtScanComDelay.setAlignment(QtCore.Qt.AlignCenter)
        self.txtScanComDelay.setObjectName("txtScanComDelay")
        self.horizontalLayout_20.addWidget(self.txtScanComDelay)
        self.lblScanComDelayUnit = QtWidgets.QLabel(self.gbScanControls)
        self.lblScanComDelayUnit.setObjectName("lblScanComDelayUnit")
        self.horizontalLayout_20.addWidget(self.lblScanComDelayUnit)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem17)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.line_5 = QtWidgets.QFrame(self.gbScanControls)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gbVScan = QtWidgets.QGroupBox(self.gbScanControls)
        self.gbVScan.setObjectName("gbVScan")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbVScan)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.gbVScan)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtVMinPos = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVMinPos.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVMinPos.setObjectName("txtVMinPos")
        self.gridLayout_3.addWidget(self.txtVMinPos, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbVScan)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtVMaxPos = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVMaxPos.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVMaxPos.setObjectName("txtVMaxPos")
        self.gridLayout_3.addWidget(self.txtVMaxPos, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gbVScan)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gbVScan)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtVStepPos = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVStepPos.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVStepPos.setObjectName("txtVStepPos")
        self.gridLayout_3.addWidget(self.txtVStepPos, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gbVScan)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gbVScan)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gbVScan)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line = QtWidgets.QFrame(self.gbVScan)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.gbVScan)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gbVScan)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gbVScan)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.txtVMaxV = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVMaxV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVMaxV.setObjectName("txtVMaxV")
        self.gridLayout.addWidget(self.txtVMaxV, 1, 1, 1, 1)
        self.txtVStepV = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVStepV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVStepV.setObjectName("txtVStepV")
        self.gridLayout.addWidget(self.txtVStepV, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gbVScan)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.txtVMinV = QtWidgets.QLineEdit(self.gbVScan)
        self.txtVMinV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtVMinV.setObjectName("txtVMinV")
        self.gridLayout.addWidget(self.txtVMinV, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gbVScan)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gbVScan)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 1, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gbVScan)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.lblVScanError = QtWidgets.QLabel(self.gbVScan)
        self.lblVScanError.setWordWrap(True)
        self.lblVScanError.setObjectName("lblVScanError")
        self.verticalLayout.addWidget(self.lblVScanError)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem18)
        self.horizontalLayout_2.addWidget(self.gbVScan)
        self.gbHScan = QtWidgets.QGroupBox(self.gbScanControls)
        self.gbHScan.setEnabled(False)
        self.gbHScan.setObjectName("gbHScan")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbHScan)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.gbHScan)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txtHMinPos = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHMinPos.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHMinPos.setObjectName("txtHMinPos")
        self.gridLayout_4.addWidget(self.txtHMinPos, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gbHScan)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gbHScan)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.txtHMaxPos = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHMaxPos.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHMaxPos.setObjectName("txtHMaxPos")
        self.gridLayout_4.addWidget(self.txtHMaxPos, 1, 1, 1, 1)
        self.txtHStepPos = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHStepPos.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHStepPos.setObjectName("txtHStepPos")
        self.gridLayout_4.addWidget(self.txtHStepPos, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gbHScan)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gbHScan)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gbHScan)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gbHScan)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.line_2 = QtWidgets.QFrame(self.gbHScan)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_14 = QtWidgets.QLabel(self.gbHScan)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txtHMaxV = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHMaxV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHMaxV.setObjectName("txtHMaxV")
        self.gridLayout_5.addWidget(self.txtHMaxV, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gbHScan)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.txtHMinV = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHMinV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHMinV.setObjectName("txtHMinV")
        self.gridLayout_5.addWidget(self.txtHMinV, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gbHScan)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gbHScan)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 2, 0, 1, 1)
        self.txtHStepV = QtWidgets.QLineEdit(self.gbHScan)
        self.txtHStepV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHStepV.setObjectName("txtHStepV")
        self.gridLayout_5.addWidget(self.txtHStepV, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gbHScan)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 0, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gbHScan)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 1, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gbHScan)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.lblHScanError = QtWidgets.QLabel(self.gbHScan)
        self.lblHScanError.setWordWrap(True)
        self.lblHScanError.setObjectName("lblHScanError")
        self.verticalLayout_2.addWidget(self.lblHScanError)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem19)
        self.horizontalLayout_2.addWidget(self.gbHScan)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.lblScanPoints = QtWidgets.QLabel(self.gbScanControls)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.lblScanPoints.setFont(font)
        self.lblScanPoints.setObjectName("lblScanPoints")
        self.verticalLayout_4.addWidget(self.lblScanPoints)
        self.lblSaveFile = QtWidgets.QLabel(self.gbScanControls)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.lblSaveFile.setFont(font)
        self.lblSaveFile.setWordWrap(True)
        self.lblSaveFile.setObjectName("lblSaveFile")
        self.verticalLayout_4.addWidget(self.lblSaveFile)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem20)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem21)
        self.btnStartStopScan = QtWidgets.QPushButton(self.gbScanControls)
        self.btnStartStopScan.setEnabled(False)
        self.btnStartStopScan.setObjectName("btnStartStopScan")
        self.horizontalLayout_3.addWidget(self.btnStartStopScan)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem22)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addWidget(self.gbScanControls)
        self.groupBox_9 = QtWidgets.QGroupBox(self.splitScan)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.rbVScanStatus = QtWidgets.QRadioButton(self.groupBox_9)
        self.rbVScanStatus.setStyleSheet("font-weight: bold")
        self.rbVScanStatus.setChecked(True)
        self.rbVScanStatus.setObjectName("rbVScanStatus")
        self.horizontalLayout_19.addWidget(self.rbVScanStatus)
        self.rbHScanStatus = QtWidgets.QRadioButton(self.groupBox_9)
        self.rbHScanStatus.setStyleSheet("font-weight: bold")
        self.rbHScanStatus.setObjectName("rbHScanStatus")
        self.horizontalLayout_19.addWidget(self.rbHScanStatus)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.splitScanInfo = QtWidgets.QSplitter(self.groupBox_9)
        self.splitScanInfo.setOrientation(QtCore.Qt.Vertical)
        self.splitScanInfo.setChildrenCollapsible(False)
        self.splitScanInfo.setObjectName("splitScanInfo")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitScanInfo)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.lyGrad = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.lyGrad.setObjectName("lyGrad")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lyScan = QtWidgets.QHBoxLayout()
        self.lyScan.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.lyScan.setObjectName("lyScan")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_43.setObjectName("label_43")
        self.lyScan.addWidget(self.label_43)
        self.lblScanStatus = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblScanStatus.sizePolicy().hasHeightForWidth())
        self.lblScanStatus.setSizePolicy(sizePolicy)
        self.lblScanStatus.setMinimumSize(QtCore.QSize(0, 0))
        self.lblScanStatus.setFrameShape(QtWidgets.QFrame.Box)
        self.lblScanStatus.setText("")
        self.lblScanStatus.setObjectName("lblScanStatus")
        self.lyScan.addWidget(self.lblScanStatus)
        self.verticalLayout_10.addLayout(self.lyScan)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_10.addWidget(self.label_44)
        self.lyGrad.addLayout(self.verticalLayout_10)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lyGrad.addWidget(self.line_3)
        self.lblColorScale = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblColorScale.sizePolicy().hasHeightForWidth())
        self.lblColorScale.setSizePolicy(sizePolicy)
        self.lblColorScale.setMinimumSize(QtCore.QSize(0, 15))
        self.lblColorScale.setMaximumSize(QtCore.QSize(16777215, 15))
        self.lblColorScale.setFrameShape(QtWidgets.QFrame.Box)
        self.lblColorScale.setText("")
        self.lblColorScale.setObjectName("lblColorScale")
        self.lyGrad.addWidget(self.lblColorScale)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblColorScaleMin = QtWidgets.QLabel(self.layoutWidget1)
        self.lblColorScaleMin.setObjectName("lblColorScaleMin")
        self.horizontalLayout_9.addWidget(self.lblColorScaleMin)
        self.lblColorScaleMid = QtWidgets.QLabel(self.layoutWidget1)
        self.lblColorScaleMid.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColorScaleMid.setObjectName("lblColorScaleMid")
        self.horizontalLayout_9.addWidget(self.lblColorScaleMid)
        self.lblColorScaleMax = QtWidgets.QLabel(self.layoutWidget1)
        self.lblColorScaleMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblColorScaleMax.setObjectName("lblColorScaleMax")
        self.horizontalLayout_9.addWidget(self.lblColorScaleMax)
        self.lyGrad.addLayout(self.horizontalLayout_9)
        self.groupBox_12 = QtWidgets.QGroupBox(self.splitScanInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lblScanProgress = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.lblScanProgress.setFont(font)
        self.lblScanProgress.setObjectName("lblScanProgress")
        self.verticalLayout_15.addWidget(self.lblScanProgress)
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_15.addWidget(self.label_23)
        self.label_38 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_15.addWidget(self.label_38)
        self.lblScanTime = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.lblScanTime.setFont(font)
        self.lblScanTime.setObjectName("lblScanTime")
        self.verticalLayout_15.addWidget(self.lblScanTime)
        self.verticalLayout_16.addWidget(self.splitScanInfo)
        self.verticalLayout_13.addWidget(self.splitScan)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1154, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.btnSaveSession = QtWidgets.QAction(MainWindow)
        self.btnSaveSession.setObjectName("btnSaveSession")
        self.btnLoadSession = QtWidgets.QAction(MainWindow)
        self.btnLoadSession.setObjectName("btnLoadSession")
        self.btnExit = QtWidgets.QAction(MainWindow)
        self.btnExit.setObjectName("btnExit")
        self.menuFile.addAction(self.btnSaveSession)
        self.menuFile.addAction(self.btnLoadSession)
        self.menuFile.addAction(self.btnExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.txtIP)
        MainWindow.setTabOrder(self.txtIP, self.txtPort)
        MainWindow.setTabOrder(self.txtPort, self.btnConnect)
        MainWindow.setTabOrder(self.btnConnect, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.btnVregTest)
        MainWindow.setTabOrder(self.btnVregTest, self.rbVCalib)
        MainWindow.setTabOrder(self.rbVCalib, self.rbHCalib)
        MainWindow.setTabOrder(self.rbHCalib, self.btnChooseFile)
        MainWindow.setTabOrder(self.btnChooseFile, self.rbVScan)
        MainWindow.setTabOrder(self.rbVScan, self.rbHScan)
        MainWindow.setTabOrder(self.rbHScan, self.rbBothScan)
        MainWindow.setTabOrder(self.rbBothScan, self.txtVMinPos)
        MainWindow.setTabOrder(self.txtVMinPos, self.txtVMaxPos)
        MainWindow.setTabOrder(self.txtVMaxPos, self.txtVStepPos)
        MainWindow.setTabOrder(self.txtVStepPos, self.txtVMinV)
        MainWindow.setTabOrder(self.txtVMinV, self.txtVMaxV)
        MainWindow.setTabOrder(self.txtVMaxV, self.txtVStepV)
        MainWindow.setTabOrder(self.txtVStepV, self.txtHMinPos)
        MainWindow.setTabOrder(self.txtHMinPos, self.txtHMaxPos)
        MainWindow.setTabOrder(self.txtHMaxPos, self.txtHStepPos)
        MainWindow.setTabOrder(self.txtHStepPos, self.txtHMinV)
        MainWindow.setTabOrder(self.txtHMinV, self.txtHMaxV)
        MainWindow.setTabOrder(self.txtHMaxV, self.txtHStepV)
        MainWindow.setTabOrder(self.txtHStepV, self.btnStartStopScan)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Current Values"))
        self.lblVerPos.setText(_translate("MainWindow", "Vertical: -- (Not calibrated)"))
        self.lblHorPos.setText(_translate("MainWindow", "Horizontal: -- (Not calibrated)"))
        self.lblV.setText(_translate("MainWindow", "Voltage: --"))
        self.lblCur.setText(_translate("MainWindow", "Current: --"))
        self.lblPollRate.setText(_translate("MainWindow", "Polling rate: --"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Server"))
        self.label_39.setText(_translate("MainWindow", "IP"))
        self.txtIP.setText(_translate("MainWindow", "10.77.0.4"))
        self.label_40.setText(_translate("MainWindow", "Port"))
        self.txtPort.setText(_translate("MainWindow", "5000"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.lblServerMsg.setText(_translate("MainWindow", "Unable to connect"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Picoammeter"))
        self.lblVerPos_2.setText(_translate("MainWindow", "Device Found"))
        self.label_57.setText(_translate("MainWindow", "Sample rate"))
        self.radioButton_3.setText(_translate("MainWindow", "Fast"))
        self.radioButton_2.setText(_translate("MainWindow", "Medium"))
        self.radioButton.setText(_translate("MainWindow", "Slow"))
        self.label_42.setText(_translate("MainWindow", "Averaging"))
        self.lineEdit.setText(_translate("MainWindow", "1"))
        self.label_56.setText(_translate("MainWindow", "Samples"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Voltage Regulator"))
        self.lblVerPos_4.setText(_translate("MainWindow", "Device Found"))
        self.btnVregTest.setText(_translate("MainWindow", "Send test signal"))
        self.lblVerPos_8.setText(_translate("MainWindow", "Response: Ok!"))
        self.gbSteppers.setTitle(_translate("MainWindow", "Stepper Motors"))
        self.rbVMove.setText(_translate("MainWindow", "Vertical"))
        self.btnRetract.setText(_translate("MainWindow", "Retract"))
        self.rbHMove.setText(_translate("MainWindow", "Horizontal"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.btnExtend.setText(_translate("MainWindow", "Extend"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Communication"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">The voltage regulator and at least one stepper motor must be calibrated before scanning.</span></p></body></html>"))
        self.gbStepperCalib.setTitle(_translate("MainWindow", "Stepper Motors"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p>Move the limit switches to the minimum and maximum position, then enter the corresponding distances from each position to the center of the beam</p></body></html>"))
        self.rbVCalib.setText(_translate("MainWindow", "Vertical"))
        self.rbHCalib.setText(_translate("MainWindow", "Horizontal"))
        self.gbVCalib.setTitle(_translate("MainWindow", "Vertical"))
        self.label.setText(_translate("MainWindow", "Upper:"))
        self.label_45.setText(_translate("MainWindow", "mm"))
        self.label_47.setText(_translate("MainWindow", "Lower:"))
        self.label_46.setText(_translate("MainWindow", "mm"))
        self.btnStartVCalib.setText(_translate("MainWindow", "Start Calibration"))
        self.lblVCalibError.setText(_translate("MainWindow", "<html><head/><body><p>TextLabel</p></body></html>"))
        self.gbHCalib.setTitle(_translate("MainWindow", "Horizontal"))
        self.label_48.setText(_translate("MainWindow", "Upper:"))
        self.label_49.setText(_translate("MainWindow", "mm"))
        self.label_50.setText(_translate("MainWindow", "Lower:"))
        self.label_52.setText(_translate("MainWindow", "mm"))
        self.btnStartHCalib.setText(_translate("MainWindow", "Start Calibration"))
        self.lblHCalibError.setText(_translate("MainWindow", "<html><head/><body><p>TextLabel</p></body></html>"))
        self.gbVolCalib.setTitle(_translate("MainWindow", "Voltage Regulator"))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p>Set the voltage on the voltage regulator, then enter the measured response in kV</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "V"))
        self.btnSetVreg.setText(_translate("MainWindow", "Set"))
        self.label_20.setText(_translate("MainWindow", "kV"))
        self.lblVolCalibError.setText(_translate("MainWindow", "TextLabel"))
        self.btnAddVregPoint.setText(_translate("MainWindow", "Add Point"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calibration"))
        self.gbFileOptions.setTitle(_translate("MainWindow", "File Options"))
        self.btnChooseFile.setText(_translate("MainWindow", "Choose Output File"))
        self.gbScanControls.setTitle(_translate("MainWindow", "Scan"))
        self.rbVScan.setText(_translate("MainWindow", "Vertical"))
        self.rbHScan.setText(_translate("MainWindow", "Horizontal"))
        self.rbBothScan.setText(_translate("MainWindow", "Both"))
        self.lblScanComDelay.setText(_translate("MainWindow", "COM Delay:"))
        self.txtScanComDelay.setText(_translate("MainWindow", "0.5"))
        self.lblScanComDelayUnit.setText(_translate("MainWindow", "seconds"))
        self.gbVScan.setTitle(_translate("MainWindow", "Vertical Scan"))
        self.label_5.setText(_translate("MainWindow", "Motor"))
        self.label_3.setText(_translate("MainWindow", "Max"))
        self.label_2.setText(_translate("MainWindow", "Min"))
        self.label_4.setText(_translate("MainWindow", "Step"))
        self.label_26.setText(_translate("MainWindow", "mm"))
        self.label_27.setText(_translate("MainWindow", "mm"))
        self.label_28.setText(_translate("MainWindow", "mm"))
        self.label_6.setText(_translate("MainWindow", "Voltage"))
        self.label_7.setText(_translate("MainWindow", "Min"))
        self.label_8.setText(_translate("MainWindow", "Max"))
        self.label_9.setText(_translate("MainWindow", "Step"))
        self.label_32.setText(_translate("MainWindow", "kV"))
        self.label_33.setText(_translate("MainWindow", "kV"))
        self.label_34.setText(_translate("MainWindow", "kV"))
        self.lblVScanError.setText(_translate("MainWindow", "TextLabel"))
        self.gbHScan.setTitle(_translate("MainWindow", "Horizontal Scan"))
        self.label_10.setText(_translate("MainWindow", "Motor"))
        self.label_11.setText(_translate("MainWindow", "Min"))
        self.label_12.setText(_translate("MainWindow", "Max"))
        self.label_13.setText(_translate("MainWindow", "Step"))
        self.label_29.setText(_translate("MainWindow", "mm"))
        self.label_30.setText(_translate("MainWindow", "mm"))
        self.label_31.setText(_translate("MainWindow", "mm"))
        self.label_14.setText(_translate("MainWindow", "Voltage"))
        self.label_16.setText(_translate("MainWindow", "Max"))
        self.label_15.setText(_translate("MainWindow", "Min"))
        self.label_17.setText(_translate("MainWindow", "Step"))
        self.label_35.setText(_translate("MainWindow", "kV"))
        self.label_36.setText(_translate("MainWindow", "kV"))
        self.label_37.setText(_translate("MainWindow", "kV"))
        self.lblHScanError.setText(_translate("MainWindow", "TextLabel"))
        self.lblScanPoints.setText(_translate("MainWindow", "Total points: --"))
        self.lblSaveFile.setText(_translate("MainWindow", "Output file not set"))
        self.btnStartStopScan.setText(_translate("MainWindow", "Start Scan"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Status"))
        self.rbVScanStatus.setText(_translate("MainWindow", "Vertical"))
        self.rbHScanStatus.setText(_translate("MainWindow", "Horizontal"))
        self.label_43.setText(_translate("MainWindow", "V"))
        self.label_44.setText(_translate("MainWindow", "mm"))
        self.lblColorScaleMin.setText(_translate("MainWindow", "--"))
        self.lblColorScaleMid.setText(_translate("MainWindow", "--"))
        self.lblColorScaleMax.setText(_translate("MainWindow", "--"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Scan Status"))
        self.lblScanProgress.setText(_translate("MainWindow", "Current: 500/1000 (50%)"))
        self.label_23.setText(_translate("MainWindow", "Vertical, +5cm"))
        self.label_38.setText(_translate("MainWindow", "Voltage: 2 kV"))
        self.lblScanTime.setText(_translate("MainWindow", "Est. Time Remaining: 5 minutes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scan"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.btnSaveSession.setText(_translate("MainWindow", "Save Session"))
        self.btnLoadSession.setText(_translate("MainWindow", "Load Session"))
        self.btnExit.setText(_translate("MainWindow", "&Exit"))

