# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/scanreviewdialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgScanView(object):
    def setupUi(self, dlgScanView):
        dlgScanView.setObjectName("dlgScanView")
        dlgScanView.resize(762, 501)
        font = QtGui.QFont()
        font.setPointSize(9)
        dlgScanView.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(dlgScanView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layoutTitle = QtWidgets.QHBoxLayout()
        self.layoutTitle.setObjectName("layoutTitle")
        self.lblScanTitle = QtWidgets.QLabel(dlgScanView)
        self.lblScanTitle.setStyleSheet("::enabled {\n"
"color:#003399;\n"
"font-size:12pt;\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"font-size:12pt;\n"
"}")
        self.lblScanTitle.setObjectName("lblScanTitle")
        self.layoutTitle.addWidget(self.lblScanTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutTitle.addItem(spacerItem)
        self.txtEditTitle = QtWidgets.QLineEdit(dlgScanView)
        self.txtEditTitle.setObjectName("txtEditTitle")
        self.layoutTitle.addWidget(self.txtEditTitle)
        self.btnEditTitle = QtWidgets.QPushButton(dlgScanView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditTitle.sizePolicy().hasHeightForWidth())
        self.btnEditTitle.setSizePolicy(sizePolicy)
        self.btnEditTitle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnEditTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnEditTitle.setStyleSheet("color:blue")
        self.btnEditTitle.setAutoDefault(True)
        self.btnEditTitle.setFlat(True)
        self.btnEditTitle.setObjectName("btnEditTitle")
        self.layoutTitle.addWidget(self.btnEditTitle)
        self.verticalLayout_3.addLayout(self.layoutTitle)
        self.lblScanKind = QtWidgets.QLabel(dlgScanView)
        self.lblScanKind.setObjectName("lblScanKind")
        self.verticalLayout_3.addWidget(self.lblScanKind)
        self.lblScanFile = QtWidgets.QLabel(dlgScanView)
        self.lblScanFile.setObjectName("lblScanFile")
        self.verticalLayout_3.addWidget(self.lblScanFile)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_25 = QtWidgets.QLabel(dlgScanView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_12.addWidget(self.label_25)
        self.line_10 = QtWidgets.QFrame(dlgScanView)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_12.addWidget(self.line_10)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.frame_2 = QtWidgets.QFrame(dlgScanView)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(104, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.lblScanStepperPoints = QtWidgets.QLabel(self.frame_2)
        self.lblScanStepperPoints.setObjectName("lblScanStepperPoints")
        self.gridLayout_2.addWidget(self.lblScanStepperPoints, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.lblScanVregPoints = QtWidgets.QLabel(self.frame_2)
        self.lblScanVregPoints.setObjectName("lblScanVregPoints")
        self.gridLayout_2.addWidget(self.lblScanVregPoints, 1, 2, 1, 1)
        self.lblScanImageSaved = QtWidgets.QLabel(self.frame_2)
        self.lblScanImageSaved.setObjectName("lblScanImageSaved")
        self.gridLayout_2.addWidget(self.lblScanImageSaved, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_26 = QtWidgets.QLabel(dlgScanView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("::enabled {\n"
"color:#003399\n"
"}\n"
"::!enabled {\n"
"color: #6699EE;\n"
"}")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.line_11 = QtWidgets.QFrame(dlgScanView)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_13.addWidget(self.line_11)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.frame = QtWidgets.QFrame(dlgScanView)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutMetadata = QtWidgets.QGridLayout(self.frame)
        self.layoutMetadata.setContentsMargins(-1, 0, 0, 0)
        self.layoutMetadata.setObjectName("layoutMetadata")
        self.verticalLayout.addWidget(self.frame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRepeatScan = QtWidgets.QPushButton(dlgScanView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRepeatScan.sizePolicy().hasHeightForWidth())
        self.btnRepeatScan.setSizePolicy(sizePolicy)
        self.btnRepeatScan.setObjectName("btnRepeatScan")
        self.horizontalLayout.addWidget(self.btnRepeatScan)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btnSave = QtWidgets.QPushButton(dlgScanView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(dlgScanView)
        QtCore.QMetaObject.connectSlotsByName(dlgScanView)

    def retranslateUi(self, dlgScanView):
        _translate = QtCore.QCoreApplication.translate
        dlgScanView.setWindowTitle(_translate("dlgScanView", "Dialog"))
        self.lblScanTitle.setText(_translate("dlgScanView", "Scan Title"))
        self.btnEditTitle.setText(_translate("dlgScanView", "Edit title..."))
        self.lblScanKind.setText(_translate("dlgScanView", "Vertical Scan"))
        self.lblScanFile.setText(_translate("dlgScanView", "FIle path"))
        self.label_25.setText(_translate("dlgScanView", "Scan settings"))
        self.label.setText(_translate("dlgScanView", "Stepper points (mm):"))
        self.lblScanStepperPoints.setText(_translate("dlgScanView", "[-1, 1], step=1"))
        self.label_2.setText(_translate("dlgScanView", "Voltage regulator points (kV):"))
        self.lblScanVregPoints.setText(_translate("dlgScanView", "[-2, 2], step=2"))
        self.lblScanImageSaved.setText(_translate("dlgScanView", "Image saved."))
        self.label_26.setText(_translate("dlgScanView", "Metadata"))
        self.btnRepeatScan.setText(_translate("dlgScanView", "Repeat scan with these settings"))
        self.btnSave.setText(_translate("dlgScanView", "Save"))

